defaults: &defaults
  docker:
    - image: circleci/node:8.11
  working_directory: ~/repo
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - build
            - package.json

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install Python
          command: |
            sudo apt-get update
            sudo apt-get install -y python-pip python-dev
      - run:
          name: Install AWS-CLI
          command: |
            sudo pip install awscli
            aws --version
      - run:
          name: Deploy to S3
          command: aws s3 sync build s3://spacex.loganarnett.com/ --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master